# https://zmk.dev/docs/config/system#snippets 

include:
  - board: corneish_zen_left//zmk # v0.3: corneish_zen_v2_left; main: corneish_zen_left//zmk - https://zmk.dev/docs/hardware
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: zenv2_Left_master
    
  - board: corneish_zen_right//zmk # v0.3: corneish_zen_v2_right; main: corneish_zen_right//zmk - https://zmk.dev/docs/hardware
    artifact-name: zenv2_Right_slave
    
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: y_niceNano_reset

  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: y_xiaoBLE_reset
    
  - board: xiao_ble//zmk # dongle switching instructions: https://docs.slicemk.com/firmware/zmk/wireless/dongle/
    shield: corneish_zen_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: xiaoBLE_master

  - board: corneish_zen_left//zmk
    cmake-args: -DCONFIG_ZMK_USB=n -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_CUSTOM_WIDGET_OUTPUT_STATUS=n -DCONFIG_CUSTOM_WIDGET_LAYER_STATUS=n -DCONFIG_CUSTOM_WIDGET_PERIPHERAL_STATUS=y -DCONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=n
    artifact-name: zenv2_Left_slave
