# https://zmk.dev/docs/config/system#snippets

include:
  - board: corneish_zen_left//zmk # was corneish_zen_v2_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corneish_zen_left
  - board: corneish_zen_right//zmk # was corneish_zen_v2_right
